#!/bin/bash

#source /opt/anaconda2/bin/activate root
#source activate py27

#install pyinstaller (does not reinstall if already installed) – sudo required on holdanddetect account
sudo pip install pyinstaller

#clone the histedlab/PumpControl repository to the desktop
cd desktop
git clone https://github.com/histedlab/PumpControl.git

#compile .app from PumpRefill.py (onefile -> bundle as .app, windowed -> do not open console window for i/o)
pyinstaller --onefile --windowed ~/Desktop/PumpControl/PumpRefill.py

#move the resulting .app from the folder created by pyinstaller to the desktop, then remove pyinstaller clutter
mv ~/desktop/dist/*.app ~/desktop
rm -R ~/desktop/build ~/desktop/dist ~/desktop/PumpControl ~/desktop/guitest.spec
